"""
Team name mapping utilities for Norsk Tipping scraper.

Norsk Tipping uses Norwegian/full team names while football-data.co.uk
uses shortened English names. This module provides mapping between the two.
"""

from __future__ import annotations

# Premier League team mappings (Norsk Tipping -> football-data.co.uk)
PREMIER_LEAGUE_TEAMS = {
    # Current teams
    "Arsenal": "Arsenal",
    "Aston Villa": "Aston Villa",
    "Bournemouth": "Bournemouth",
    "Brentford": "Brentford",
    "Brighton and Hove Albion": "Brighton",
    "Brighton": "Brighton",
    "Burnley": "Burnley",
    "Chelsea": "Chelsea",
    "Crystal Palace": "Crystal Palace",
    "Everton": "Everton",
    "Fulham": "Fulham",
    "Ipswich Town": "Ipswich",
    "Ipswich": "Ipswich",
    "Leeds United": "Leeds",
    "Leeds": "Leeds",
    "Leicester City": "Leicester",
    "Leicester": "Leicester",
    "Liverpool": "Liverpool",
    "Luton Town": "Luton",
    "Luton": "Luton",
    "Manchester City": "Man City",
    "Manchester United": "Man United",
    "Newcastle United": "Newcastle",
    "Newcastle": "Newcastle",
    "Norwich City": "Norwich",
    "Norwich": "Norwich",
    "Nottingham Forest": "Nott'm Forest",
    "Sheffield United": "Sheffield United",
    "Southampton": "Southampton",
    "Sunderland": "Sunderland",
    "Tottenham Hotspur": "Tottenham",
    "Tottenham": "Tottenham",
    "Watford": "Watford",
    "West Ham United": "West Ham",
    "West Ham": "West Ham",
    "Wolverhampton Wanderers": "Wolves",
    "Wolverhampton": "Wolves",
    "Wolves": "Wolves",
}

# Championship (E1)
CHAMPIONSHIP_TEAMS = {
    "Barnsley": "Barnsley",
    "Barnsley FC": "Barnsley",
    "Birmingham City": "Birmingham",
    "Birmingham": "Birmingham",
    "Blackburn Rovers": "Blackburn",
    "Blackburn": "Blackburn",
    "Blackpool": "Blackpool",
    "Blackpool FC": "Blackpool",
    "Bristol City": "Bristol City",
    "Cardiff City": "Cardiff",
    "Cardiff": "Cardiff",
    "Coventry City": "Coventry",
    "Coventry": "Coventry",
    "Derby County": "Derby",
    "Derby": "Derby",
    "Huddersfield Town": "Huddersfield",
    "Huddersfield": "Huddersfield",
    "Hull City": "Hull",
    "Hull": "Hull",
    "Middlesbrough": "Middlesbrough",
    "Millwall": "Millwall",
    "Preston North End": "Preston",
    "Preston": "Preston",
    "Queens Park Rangers": "QPR",
    "QPR": "QPR",
    "Reading": "Reading",
    "Sheffield Wednesday": "Sheffield Weds",
    "Stoke City": "Stoke",
    "Stoke": "Stoke",
    "Swansea City": "Swansea",
    "Swansea": "Swansea",
    "West Bromwich Albion": "West Brom",
    "West Bromwich": "West Brom",
    "West Brom": "West Brom",
    "Oxford United": "Oxford",
    "Oxford": "Oxford",
    "Portsmouth": "Portsmouth",
    "Plymouth Argyle": "Plymouth",
    "Plymouth": "Plymouth",
    "Wrexham": "Wrexham",
}

# League One (E2)
LEAGUE_ONE_TEAMS = {
    "Wigan Athletic": "Wigan",
    "Wigan": "Wigan",
    "Bolton Wanderers": "Bolton",
    "Bolton": "Bolton",
    "Peterborough United": "Peterboro",
    "Peterborough": "Peterboro",
    "Rotherham United": "Rotherham",
    "Rotherham": "Rotherham",
    "Wycombe Wanderers": "Wycombe",
    "Wycombe": "Wycombe",
    "Exeter City": "Exeter",
    "Exeter": "Exeter",
    "Northampton Town": "Northampton",
    "Northampton": "Northampton",
    "Leyton Orient": "Leyton Orient",
    "Lincoln City": "Lincoln",
    "Lincoln": "Lincoln",
    "Stockport County FC": "Stockport",
    "Stockport County": "Stockport",
    "Stockport": "Stockport",
    "Charlton Athletic": "Charlton",
    "Charlton": "Charlton",
    "Bristol Rovers": "Bristol Rvs",
    "Cambridge United": "Cambridge",
    "Cambridge": "Cambridge",
    "Mansfield Town": "Mansfield",
    "Mansfield": "Mansfield",
    "Barnsley FC": "Barnsley",
}

# League Two (E3)
LEAGUE_TWO_TEAMS = {
    "AFC Wimbledon": "AFC Wimbledon",
    "Doncaster Rovers": "Doncaster",
    "Doncaster": "Doncaster",
    "Port Vale": "Port Vale",
    "Bradford City FC": "Bradford",
    "Bradford City": "Bradford",
    "Bradford": "Bradford",
    "Crewe Alexandra": "Crewe",
    "Crewe": "Crewe",
    "Grimsby Town": "Grimsby",
    "Grimsby": "Grimsby",
    "Tranmere Rovers FC": "Tranmere",
    "Tranmere Rovers": "Tranmere",
    "Tranmere": "Tranmere",
    "Accrington Stanley": "Accrington",
    "Accrington": "Accrington",
    "Fleetwood Town": "Fleetwood Town",
    "Fleetwood": "Fleetwood Town",
    "Colchester United": "Colchester",
    "Colchester": "Colchester",
    "Cheltenham Town": "Cheltenham",
    "Cheltenham": "Cheltenham",
    "Gillingham": "Gillingham",
    "Swindon Town": "Swindon",
    "Swindon": "Swindon",
    "Notts County": "Notts County",
    "Salford City": "Salford",
    "Salford": "Salford",
    "Crawley Town": "Crawley Town",
    "Crawley": "Crawley Town",
    "Newport County": "Newport County",
    "Newport": "Newport County",
    "Harrogate Town": "Harrogate",
    "Harrogate": "Harrogate",
    "Barrow AFC": "Barrow",
    "Barrow": "Barrow",
    "Stevenage": "Stevenage",
    "Milton Keynes Dons": "Milton Keynes Dons",
    "MK Dons": "Milton Keynes Dons",
    "Walsall FC": "Walsall",
    "Walsall": "Walsall",
    "Shrewsbury Town": "Shrewsbury",
    "Shrewsbury": "Shrewsbury",
    "Barnet FC": "Barnet",
    "Barnet": "Barnet",
    "Bromley FC": "Bromley",
    "Bromley": "Bromley",
    "Chesterfield FC": "Chesterfield",
    "Chesterfield": "Chesterfield",
    "Burton Albion": "Burton",
    "Burton": "Burton",
    "Morecambe": "Morecambe",
    "Oldham Athletic": "Oldham",
    "Oldham": "Oldham",
}

# La Liga (SP1)
LA_LIGA_TEAMS = {
    "Athletic Club": "Ath Bilbao",
    "Athletic Club Bilbao": "Ath Bilbao",
    "Athletic Bilbao": "Ath Bilbao",
    "Atlético Madrid": "Ath Madrid",
    "Atletico Madrid": "Ath Madrid",
    "Barcelona": "Barcelona",
    "Deportivo Alavés": "Alaves",
    "Alaves": "Alaves",
    "Getafe": "Getafe",
    "Girona": "Girona",
    "Real Betis": "Betis",
    "Betis": "Betis",
    "Real Madrid": "Real Madrid",
    "Real Sociedad": "Sociedad",
    "Sevilla": "Sevilla",
    "Valencia": "Valencia",
    "Villarreal": "Villarreal",
    "Celta Vigo": "Celta",
    "Celta": "Celta",
    "Rayo Vallecano": "Vallecano",
    "Osasuna": "Osasuna",
    "Espanyol": "Espanol",
    "Las Palmas": "Las Palmas",
    "Mallorca": "Mallorca",
    "Leganés": "Leganes",
    "Leganes": "Leganes",
    "Valladolid": "Valladolid",
}

# La Liga 2 (SP2)
LA_LIGA_2_TEAMS = {
    "Elche": "Elche",
    "Levante": "Levante",
    "Granada": "Granada",
    "Almeria": "Almeria",
    "Huesca": "Huesca",
    "Malaga": "Malaga",
    "Cadiz": "Cadiz",
    "Eibar": "Eibar",
    "Real Oviedo": "Oviedo",
    "Oviedo": "Oviedo",
    "Real Zaragoza": "Zaragoza",
    "Zaragoza": "Zaragoza",
    "Racing Santander": "Santander",
    "Santander": "Santander",
    "Deportivo La Coruna": "La Coruna",
    "Deportivo": "La Coruna",
    "Sp Gijon": "Sp Gijon",
    "Gijon": "Sp Gijon",
    "Sporting Gijon": "Sp Gijon",
    "Albacete": "Albacete",
    "Burgos": "Burgos",
    "Mirandes": "Mirandes",
    "Real Sociedad B": "Sociedad B",
    "Cordoba": "Cordoba",
    "Castellon": "Castellon",
    "Cartagena": "Cartagena",
    "FC Andorra": "Andorra",
    "Andorra": "Andorra",
    "CD Leonesa": "Cultural Leonesa",
    "Cultural Leonesa": "Cultural Leonesa",
    "Tenerife": "Tenerife",
    "Ponferradina": "Ponferradina",
    "Ferrol": "Ferrol",
    "Eldense": "Eldense",
}

# Bundesliga (D1)
BUNDESLIGA_TEAMS = {
    "Bayern München": "Bayern Munich",
    "Bayern Munich": "Bayern Munich",
    "Bayern Munchen": "Bayern Munich",
    "Borussia Dortmund": "Dortmund",
    "Dortmund": "Dortmund",
    "RB Leipzig": "RB Leipzig",
    "Leipzig": "RB Leipzig",
    "Bayer 04 Leverkusen": "Leverkusen",
    "Bayer Leverkusen": "Leverkusen",
    "Leverkusen": "Leverkusen",
    "Eintracht Frankfurt": "Ein Frankfurt",
    "Frankfurt": "Ein Frankfurt",
    "VfL Wolfsburg": "Wolfsburg",
    "Wolfsburg": "Wolfsburg",
    "Borussia Mönchengladbach": "M'gladbach",
    "Borussia Monchengladbach": "M'gladbach",
    "Monchengladbach": "M'gladbach",
    "TSG 1899 Hoffenheim": "Hoffenheim",
    "Hoffenheim": "Hoffenheim",
    "SC Freiburg": "Freiburg",
    "Freiburg": "Freiburg",
    "VfB Stuttgart": "Stuttgart",
    "Stuttgart": "Stuttgart",
    "1. FC Union Berlin": "Union Berlin",
    "Union Berlin": "Union Berlin",
    "1. FC Köln": "FC Koln",
    "FC Köln": "FC Koln",
    "Köln": "FC Koln",
    "Koln": "FC Koln",
    "FSV Mainz 05": "Mainz",
    "FSV Mainz": "Mainz",
    "Mainz 05": "Mainz",
    "Mainz": "Mainz",
    "FC Augsburg": "Augsburg",
    "Augsburg": "Augsburg",
    "VfL Bochum": "Bochum",
    "Bochum": "Bochum",
    "Werder Bremen": "Werder Bremen",
    "Bremen": "Werder Bremen",
    "FC St. Pauli": "St Pauli",
    "St Pauli": "St Pauli",
    "Holstein Kiel": "Holstein Kiel",
    "Kiel": "Holstein Kiel",
    "Heidenheim": "Heidenheim",
    "Hertha BSC": "Hertha",
    "Hertha Berlin": "Hertha",
    "Hertha": "Hertha",
}

# Bundesliga 2 (D2)
BUNDESLIGA_2_TEAMS = {
    "Hamburger SV": "Hamburg",
    "Hamburg": "Hamburg",
    "HSV": "Hamburg",
    "Hannover 96": "Hannover",
    "Hannover": "Hannover",
    "Karlsruher SC": "Karlsruhe",
    "Karlsruhe": "Karlsruhe",
    "Fortuna Düsseldorf": "Fortuna Dusseldorf",
    "Fortuna Dusseldorf": "Fortuna Dusseldorf",
    "Düsseldorf": "Fortuna Dusseldorf",
    "Dusseldorf": "Fortuna Dusseldorf",
    "1. FC Nürnberg": "Nurnberg",
    "Nürnberg": "Nurnberg",
    "Nurnberg": "Nurnberg",
    "SC Paderborn": "Paderborn",
    "Paderborn": "Paderborn",
    "Schalke 04": "Schalke 04",
    "Schalke": "Schalke 04",
    "Greuther Fürth": "Greuther Furth",
    "Greuther Furth": "Greuther Furth",
    "Fürth": "Greuther Furth",
    "1. FC Magdeburg": "Magdeburg",
    "Magdeburg": "Magdeburg",
    "Eintracht Braunschweig": "Braunschweig",
    "Braunschweig": "Braunschweig",
    "1 FC Kaiserslautern": "Kaiserslautern",
    "1. FC Kaiserslautern": "Kaiserslautern",
    "Kaiserslautern": "Kaiserslautern",
    "SV Darmstadt 98": "Darmstadt",
    "Darmstadt": "Darmstadt",
    "SV 07 Elversberg": "Elversberg",
    "Elversberg": "Elversberg",
    "SC Preussen 06 Munster": "Preußen Münster",
    "Preussen Munster": "Preußen Münster",
    "Münster": "Preußen Münster",
    "Dynamo Dresden": "Dresden",
    "Dresden": "Dresden",
    "SV Wehen Wiesbaden": "Wehen",
    "Wehen Wiesbaden": "Wehen",
    "Wehen": "Wehen",
    "Arminia Bielefeld": "Bielefeld",
    "Bielefeld": "Bielefeld",
    "Erzgebirge Aue": "Erzgebirge Aue",
    "Aue": "Erzgebirge Aue",
    "Regensburg": "Regensburg",
    "Jahn Regensburg": "Regensburg",
    "Ulm": "Ulm",
    "SSV Ulm": "Ulm",
}

# Serie A (I1)
SERIE_A_TEAMS = {
    "AC Milan": "Milan",
    "Milan": "Milan",
    "Inter Milan": "Inter",
    "Inter": "Inter",
    "Juventus": "Juventus",
    "Napoli": "Napoli",
    "AS Roma": "Roma",
    "Roma": "Roma",
    "Lazio": "Lazio",
    "Atalanta": "Atalanta",
    "Atalanta BC": "Atalanta",
    "Fiorentina": "Fiorentina",
    "Bologna": "Bologna",
    "Torino": "Torino",
    "Udinese": "Udinese",
    "Sassuolo": "Sassuolo",
    "Sassuolo Calcio": "Sassuolo",
    "Empoli": "Empoli",
    "Cagliari": "Cagliari",
    "Hellas Verona": "Verona",
    "Verona": "Verona",
    "Genoa": "Genoa",
    "Lecce": "Lecce",
    "Monza": "Monza",
    "AC Monza": "Monza",
    "Como": "Como",
    "Parma": "Parma",
    "Venezia": "Venezia",
}

# Serie B (I2)
SERIE_B_TEAMS = {
    "Pisa SC": "Pisa",
    "Pisa": "Pisa",
    "Spezia Calcio": "Spezia",
    "Spezia": "Spezia",
    "US Cremonese": "Cremonese",
    "Cremonese": "Cremonese",
    "Sampdoria Genoa": "Sampdoria",
    "Sampdoria": "Sampdoria",
    "Palermo FC": "Palermo",
    "Palermo": "Palermo",
    "Frosinone Calcio": "Frosinone",
    "Frosinone": "Frosinone",
    "SSC Bari": "Bari",
    "Bari": "Bari",
    "Modena FC": "Modena",
    "Modena": "Modena",
    "Reggiana 1919": "Reggiana",
    "Reggiana": "Reggiana",
    "Cesena FC": "Cesena",
    "Cesena": "Cesena",
    "Mantova 1911": "Mantova",
    "Mantova": "Mantova",
    "Carrarese Calcio": "Carrarese",
    "Carrarese": "Carrarese",
    "US Catanzaro": "Catanzaro",
    "Catanzaro": "Catanzaro",
    "Juve Stabia": "Juve Stabia",
    "FC Sudtirol Bolzano": "Sudtirol",
    "Sudtirol": "Sudtirol",
    "Salernitana": "Salernitana",
    "Cittadella": "Cittadella",
    "Brescia": "Brescia",
    "Cosenza": "Cosenza",
}

# Ligue 1 (F1)
LIGUE_1_TEAMS = {
    "Paris Saint-Germain": "Paris SG",
    "PSG": "Paris SG",
    "Marseille": "Marseille",
    "Olympique Marseille": "Marseille",
    "Lyon": "Lyon",
    "Olympique Lyon": "Lyon",
    "Monaco": "Monaco",
    "AS Monaco": "Monaco",
    "Lille": "Lille",
    "Lille OSC": "Lille",
    "Nice": "Nice",
    "OGC Nice": "Nice",
    "Rennes": "Rennes",
    "Stade Rennais": "Rennes",
    "Lens": "Lens",
    "RC Lens": "Lens",
    "Montpellier": "Montpellier",
    "Strasbourg": "Strasbourg",
    "Strasbourg Alsace": "Strasbourg",
    "Nantes": "Nantes",
    "FC Nantes": "Nantes",
    "Reims": "Reims",
    "Stade Reims": "Reims",
    "Brest": "Brest",
    "Stade Brest 29": "Brest",
    "Toulouse": "Toulouse",
    "Le Havre": "Le Havre",
    "Auxerre": "Auxerre",
    "AJ Auxerre": "Auxerre",
    "Angers": "Angers",
    "Angers SCO": "Angers",
    "Saint-Étienne": "St Etienne",
    "St Etienne": "St Etienne",
}

# Ligue 2 (F2)
LIGUE_2_TEAMS = {
    "FC Metz": "Metz",
    "Metz": "Metz",
    "Paris FC": "Paris FC",
    "FC Lorient": "Lorient",
    "Lorient": "Lorient",
    "Caen": "Caen",
    "SM Caen": "Caen",
    "Bordeaux": "Bordeaux",
    "Girondins Bordeaux": "Bordeaux",
    "Grenoble": "Grenoble",
    "Grenoble Foot": "Grenoble",
    "Amiens": "Amiens",
    "Amiens SC": "Amiens",
    "Rodez": "Rodez",
    "Laval": "Laval",
    "Stade Laval": "Laval",
    "Ajaccio": "Ajaccio",
    "AC Ajaccio": "Ajaccio",
    "Pau FC": "Pau FC",
    "Pau": "Pau FC",
    "Guingamp": "Guingamp",
    "EA Guingamp": "Guingamp",
    "Dunkerque": "Dunkerque",
    "USL Dunkerque": "Dunkerque",
    "Bastia": "Bastia",
    "SC Bastia": "Bastia",
    "Annecy": "Annecy",
    "FC Annecy": "Annecy",
    "Troyes": "Troyes",
    "ES Troyes": "Troyes",
    "Martigues": "Martigues",
    "FC Martigues": "Martigues",
}

# Scottish Premiership
SCOTTISH_TEAMS = {
    "Celtic": "Celtic",
    "Rangers": "Rangers",
    "Aberdeen": "Aberdeen",
    "Heart of Midlothian FC": "Hearts",
    "Hearts": "Hearts",
    "Hibernian": "Hibernian",
    "Hibs": "Hibernian",
    "Motherwell FC": "Motherwell",
    "Motherwell": "Motherwell",
    "Dundee FC": "Dundee",
    "Dundee": "Dundee",
    "Dundee United": "Dundee United",
    "Kilmarnock FC": "Kilmarnock",
    "Kilmarnock": "Kilmarnock",
    "St Mirren FC": "St Mirren",
    "St Mirren": "St Mirren",
    "St Johnstone": "St Johnstone",
    "Ross County": "Ross County",
    "Livingston": "Livingston",
    "Partick Thistle": "Partick",
    "Partick": "Partick",
}

# Dutch Eredivisie
EREDIVISIE_TEAMS = {
    "Ajax Amsterdam": "Ajax",
    "Ajax": "Ajax",
    "PSV Eindhoven": "PSV Eindhoven",
    "PSV": "PSV Eindhoven",
    "Feyenoord Rotterdam": "Feyenoord",
    "Feyenoord": "Feyenoord",
    "AZ Alkmaar": "AZ Alkmaar",
    "AZ": "AZ Alkmaar",
    "FC Twente Enschede": "Twente",
    "FC Twente": "Twente",
    "Twente": "Twente",
    "FC Utrecht": "Utrecht",
    "Utrecht": "Utrecht",
    "Go Ahead Eagles": "Go Ahead Eagles",
    "SC Heerenveen": "Heerenveen",
    "Heerenveen": "Heerenveen",
    "Fortuna Sittard": "For Sittard",
    "Sittard": "For Sittard",
    "NEC Nijmegen": "Nijmegen",
    "NEC": "Nijmegen",
    "Nijmegen": "Nijmegen",
    "Sparta Rotterdam": "Sparta Rotterdam",
    "Sparta": "Sparta Rotterdam",
    "PEC Zwolle": "Zwolle",
    "Zwolle": "Zwolle",
    "Heracles Almelo": "Heracles",
    "Heracles": "Heracles",
    "NAC Breda": "NAC Breda",
    "NAC": "NAC Breda",
    "FC Groningen": "Groningen",
    "Groningen": "Groningen",
    "Willem II Tilburg": "Willem II",
    "Willem II": "Willem II",
    "FC Volendam": "Volendam",
    "Volendam": "Volendam",
    "Excelsior Rotterdam": "Excelsior",
    "Excelsior": "Excelsior",
    "Vitesse": "Vitesse",
    "RKC Waalwijk": "Waalwijk",
    "Waalwijk": "Waalwijk",
    "SC Cambuur": "Cambuur",
    "Cambuur": "Cambuur",
    "FC Emmen": "FC Emmen",
    "Emmen": "FC Emmen",
    "Almere City": "Almere City",
}

# Dutch Eerste Divisie (second tier)
EERSTE_DIVISIE_TEAMS = {
    "SC Telstar": "Telstar",
    "Telstar": "Telstar",
    "Jong Utrecht": "Utrecht",  # Reserve team
    "Jong AZ": "AZ Alkmaar",  # Reserve team
    "ADO Den Haag": "ADO Den Haag",
    "ADO": "ADO Den Haag",
    "FC Den Bosch": "FC Den Bosch",
    "Den Bosch": "FC Den Bosch",
    "FC Dordrecht": "FC Dordrecht",
    "Dordrecht": "FC Dordrecht",
    "VVV Venlo": "VVV Venlo",
    "Venlo": "VVV Venlo",
    "Helmond Sport": "Helmond Sport",
    "Helmond": "Helmond Sport",
}

# Portuguese Primeira Liga
PORTUGUESE_TEAMS = {
    "Benfica": "Benfica",
    "SL Benfica": "Benfica",
    "Porto": "Porto",
    "FC Porto": "Porto",
    "Sporting CP": "Sp Lisbon",
    "Sporting Lisbon": "Sp Lisbon",
    "Sporting": "Sp Lisbon",
    "SC Braga": "Sp Braga",
    "Braga": "Sp Braga",
    "Vitoria SC Guimaraes": "Guimaraes",
    "Vitoria Guimaraes": "Guimaraes",
    "Guimaraes": "Guimaraes",
    "Rio Ave": "Rio Ave",
    "Gil Vicente Barcelos": "Gil Vicente",
    "Gil Vicente": "Gil Vicente",
    "Famalicao": "Famalicao",
    "FC Famalicao": "Famalicao",
    "Santa Clara Azores": "Santa Clara",
    "Santa Clara": "Santa Clara",
    "Estoril Praia": "Estoril",
    "Estoril": "Estoril",
    "FC Arouca": "Arouca",
    "Arouca": "Arouca",
    "Casa Pia Lisbon": "Casa Pia",
    "Casa Pia": "Casa Pia",
    "Moreirense": "Moreirense",
    "CD Nacional Madeira": "Nacional",
    "Nacional": "Nacional",
    "Boavista": "Boavista",
    "Estrela Amadora": "Estrela",
    "Estrela": "Estrela",
    "AVS Futebol SAD": "AVS",
    "AVS": "AVS",
    "Farense": "Farense",
    "CD Tondela": "Tondela",
    "Tondela": "Tondela",
    "Vizela": "Vizela",
    "Chaves": "Chaves",
    "Portimonense": "Portimonense",
    "Pacos Ferreira": "Pacos Ferreira",
    "Maritimo": "Maritimo",
}

# Turkish Süper Lig
TURKISH_TEAMS = {
    "Galatasaray Istanbul": "Galatasaray",
    "Galatasaray": "Galatasaray",
    "Fenerbahce Istanbul": "Fenerbahce",
    "Fenerbahce": "Fenerbahce",
    "Besiktas Istanbul": "Besiktas",
    "Besiktas": "Besiktas",
    "Trabzonspor": "Trabzonspor",
    "Istanbul Basaksehir": "Buyuksehyr",
    "Basaksehir": "Buyuksehyr",
    "Antalyaspor": "Antalyaspor",
    "Konyaspor": "Konyaspor",
    "Alanyaspor": "Alanyaspor",
    "Kasimpasa Istanbul": "Kasimpasa",
    "Kasimpasa": "Kasimpasa",
    "Gaziantep": "Gaziantep",
    "Gaziantep FK": "Gaziantep",
    "Caykur Rizespor": "Rizespor",
    "Rizespor": "Rizespor",
    "Sivasspor": "Sivasspor",
    "Kayserispor": "Kayserispor",
    "Samsunspor": "Samsunspor",
    "Goztepe Izmir": "Goztep",
    "Goztepe": "Goztep",
    "Eyupspor": "Eyupspor",
    "Fatih Karagumruk Istanbul": "Karagumruk",
    "Karagumruk": "Karagumruk",
    "Genclerbirligi": "Genclerbirligi",
    "Ankaragucu": "Ankaragucu",
    "Hatayspor": "Hatayspor",
    "Giresunspor": "Giresunspor",
    "Kocaelispor": "Kocaelispor",
    "Adana Demirspor": "Ad. Demirspor",
    "Pendikspor": "Pendikspor",
    "Istanbulspor": "Istanbulspor",
    "Bodrumspor": "Bodrumspor",
}

# Belgian Pro League
BELGIAN_TEAMS = {
    "Club Brugge": "Club Brugge",
    "RSC Anderlecht": "Anderlecht",
    "Anderlecht": "Anderlecht",
    "Union Saint-Gilloise": "St. Gilloise",
    "Union St-Gilloise": "St. Gilloise",
    "St. Gilloise": "St. Gilloise",
    "KRC Genk": "Genk",
    "Genk": "Genk",
    "Royal Antwerp FC": "Antwerp",
    "Antwerp": "Antwerp",
    "KAA Gent": "Gent",
    "Gent": "Gent",
    "Standard Liege": "Standard",
    "Standard": "Standard",
    "Cercle Brugge": "Cercle Brugge",
    "Yellow-Red KV Mechelen": "Mechelen",
    "KV Mechelen": "Mechelen",
    "Mechelen": "Mechelen",
    "KVC Westerlo": "Westerlo",
    "Westerlo": "Westerlo",
    "Royal Charleroi SC": "Charleroi",
    "Charleroi": "Charleroi",
    "Oud-Heverlee Leuven": "Oud-Heverlee Leuven",
    "OH Leuven": "Oud-Heverlee Leuven",
    "Leuven": "Oud-Heverlee Leuven",
    "St. Truidense VV": "St Truiden",
    "St-Truiden": "St Truiden",
    "STVV": "St Truiden",
    "SV Zulte Waregem": "Waregem",
    "Zulte Waregem": "Waregem",
    "Waregem": "Waregem",
    "KAS Eupen": "Eupen",
    "Eupen": "Eupen",
    "K Beerschot VA": "Beerschot VA",
    "Beerschot": "Beerschot VA",
    "KV Kortrijk": "Kortrijk",
    "Kortrijk": "Kortrijk",
    "KV Oostende": "Oostende",
    "Oostende": "Oostende",
    "FCV Dender EH": "Dender",
    "Dender": "Dender",
    "RAAL La Louviere": "RAAL La Louviere",
    "La Louviere": "RAAL La Louviere",
    "RFC Liege": "RFC Liege",
    "Seraing": "Seraing",
    "Lommel SK": "Lommel SK",
    "Lommel": "Lommel SK",
    "RWD Molenbeek": "RWD Molenbeek",
    "Molenbeek": "RWD Molenbeek",
}

# Greek Super League
GREEK_TEAMS = {
    "Olympiakos": "Olympiakos",
    "Olympiacos": "Olympiakos",
    "PAOK": "PAOK",
    "Panathinaikos": "Panathinaikos",
    "AEK Athens": "AEK",
    "AEK": "AEK",
    "Aris": "Aris",
    "Aris Thessaloniki": "Aris",
    "Asteras Tripolis": "Asteras Tripolis",
    "Atromitos": "Atromitos",
    "OFI Crete": "OFI Crete",
    "OFI": "OFI Crete",
    "Volos NFC": "Volos NFC",
    "Volos": "Volos NFC",
    "Lamia": "Lamia",
    "Giannina": "Giannina",
    "PAS Giannina": "Giannina",
    "Ionikos": "Ionikos",
    "Panetolikos": "Panetolikos",
    "Levadiakos": "Levadeiakos",
    "Apollon Smyrnis": "Apollon",
    "Athens Kallithea": "Athens Kallithea",
    "Panserraikos": "Panserraikos",
    "Kifisia": "Kifisia",
    "Larisa": "Larisa",
}

# UEFA European competitions
UEFA_TEAMS = {
    # Champions League teams
    "Atletico Madrid": "Ath Madrid",
    "Atalanta BC": "Atalanta",
    "Inter Milan": "Inter",
    "AC Milan": "Milan",
    "AS Roma": "Roma",
    "Roma": "Roma",
    "Juventus Turin": "Juventus",
    "Real Madrid CF": "Real Madrid",
    "FC Barcelona": "Barcelona",
    # Europa League / Conference League teams
    "Shakhtar Donetsk": "Shakhtar Donetsk",
    "Dinamo Zagreb": "Dinamo Zagreb",
    "Dinamo Kyiv": "Dinamo Kyiv",
    "Dynamo Kyiv": "Dynamo Kyiv",
    "Dynamo Kiev": "Dynamo Kyiv",
    "Red Bull Salzburg": "Red Bull Salzburg",
    "Salzburg": "Red Bull Salzburg",
    "Young Boys": "Young Boys",
    "FC Basel": "FC Basel",
    "Basel": "FC Basel",
    "Sturm Graz": "Sturm Graz",
    "Rapid Wien": "Rapid Wien",
    "Rapid Vienna": "Rapid Wien",
    "KS Rakow Czestochowa": "Rakow",
    "Rakow Czestochowa": "Rakow",
    "Rakow": "Rakow",
    "Slovan Bratislava": "Slovan Bratislava",
    "Ferencvaros": "Ferencvaros",
    "Ferencvaros TC": "Ferencvaros",
    "Viktoria Plzen": "Viktoria Plzen",
    "Plzen": "Viktoria Plzen",
    "Sparta Praha": "Sparta Praha",
    "Sparta Prague": "Sparta Praha",
    "FC Midtjylland": "FC Midtjylland",
    "Midtjylland": "FC Midtjylland",
    "FC Copenhagen": "FC Copenhagen",
    "Copenhagen": "FC Copenhagen",
    "Malmö FF": "Malmö FF",
    "Malmo": "Malmö FF",
    "Malmö": "Malmö FF",
    "Ludogorets 1947": "Ludogorets 1947",
    "Ludogorets": "Ludogorets 1947",
    "FCSB": "FCSB",
    "Steaua Bucuresti": "FCSB",
    "Røde Stjerne": "Red Star",
    "Red Star Belgrade": "Red Star",
    "Crvena Zvezda": "Red Star",
    "Maccabi Tel Aviv": "Maccabi Tel Aviv",
    "Maccabi Haifa": "Maccabi Haifa",
    "Sheriff Tiraspol": "Sheriff Tiraspol",
    "Sheriff": "Sheriff Tiraspol",
    "HJK Helsinki": "HJK Helsinki",
    "Qarabag": "Qarabag",
    # Conference League teams 2025-26
    "HNK Rijeka": "Rijeka",
    "Rijeka": "Rijeka",
    "NK Celje": "Celje",
    "Celje": "Celje",
    "Jagiellonia Bialystok": "Jagiellonia",
    "Jagiellonia": "Jagiellonia",
    "CS Universitatea Craiova": "U Craiova",
    "U Craiova": "U Craiova",
    "SK Sigma Olomouc": "Sigma Olomouc",
    "Sigma Olomouc": "Sigma Olomouc",
    "Mainz 05": "Mainz",
    "1. FSV Mainz 05": "Mainz",
    "Samsunspor": "Samsunspor",
    "Breidablik": "Breidablik",
    "KuPS": "KuPS",
    "Kuopio PS": "KuPS",
    "AEK Larnaca": "AEK Larnaca",
    "AEK Larnaka": "AEK Larnaca",
    # Other European teams
    "Hamrun Spartans": "Hamrun Spartans",
    "Lincoln Red Imps FC": "Lincoln Red Imps",
    "Lincoln Red Imps": "Lincoln Red Imps",
    "KF Drita": "Drita",
    "Drita": "Drita",
    "Shkendija": "Shkendija",
    "FK Shkendija": "Shkendija",
    "FK Noah Yerevan": "Noah",
    "Noah": "Noah",
    "FC Noah": "Noah",
}

# Norwegian Eliteserien (Norsk Tipping name -> football-data.co.uk name)
NORWEGIAN_TEAMS = {
    # Norsk Tipping uses Norwegian characters, football-data uses ASCII
    "Bodø/Glimt": "Bodo/Glimt",
    "Bodo/Glimt": "Bodo/Glimt",
    "Brann": "Brann",
    "SK Brann": "Brann",
    "Fredrikstad": "Fredrikstad",
    "HamKam": "HamKam",
    "Hamarkameratene": "HamKam",
    "Haugesund": "Haugesund",
    "FK Haugesund": "Haugesund",
    "KFUM": "KFUM Oslo",
    "KFUM Oslo": "KFUM Oslo",
    "Kristiansund": "Kristiansund",
    "Kristiansund BK": "Kristiansund",
    "Lillestrøm": "Lillestrom",
    "Lillestrom": "Lillestrom",
    "Lillestrøm SK": "Lillestrom",
    "Molde": "Molde",
    "Molde FK": "Molde",
    "Moss": "Moss",
    "Moss FK": "Moss",
    "Odd": "Odd",
    "Odds BK": "Odd",
    "Rosenborg": "Rosenborg",
    "Rosenborg BK": "Rosenborg",
    "Sandefjord": "Sandefjord",
    "Sandefjord Fotball": "Sandefjord",
    "Sarpsborg 08": "Sarpsborg 08",
    "Sarpsborg": "Sarpsborg 08",
    "Strømsgodset": "Stromsgodset",
    "Stromsgodset": "Stromsgodset",
    "Strømsgodset IF": "Stromsgodset",
    "Tromsø": "Tromso",
    "Tromso": "Tromso",
    "Tromsø IL": "Tromso",
    "Viking": "Viking",
    "Viking FK": "Viking",
    "Vålerenga": "Valerenga",
    "Valerenga": "Valerenga",
    "Aalesund": "Aalesund",
    "Aalesunds FK": "Aalesund",
    "Start": "Start",
    "IK Start": "Start",
    "Stabæk": "Stabaek",
    "Stabaek": "Stabaek",
    "Ranheim": "Ranheim",
    "Ranheim TF": "Ranheim",
    "Mjøndalen": "Mjondalen",
    "Mjondalen": "Mjondalen",
    # OBOS-ligaen (Norwegian 2nd division)
    "Bryne": "Bryne",
    "Bryne FK": "Bryne",
    "Sogndal": "Sogndal",
    "Sogndal IL": "Sogndal",
    "Kongsvinger": "Kongsvinger",
    "Kongsvinger IL": "Kongsvinger",
    "Jerv": "Jerv",
    "FK Jerv": "Jerv",
    "Sandnes Ulf": "Sandnes Ulf",
}

# Swedish Allsvenskan
SWEDISH_TEAMS = {
    "Malmö FF": "Malmo",
    "Malmö": "Malmo",
    "Malmo FF": "Malmo",
    "AIK": "AIK",
    "AIK Stockholm": "AIK",
    "Djurgården": "Djurgarden",
    "Djurgarden": "Djurgarden",
    "Djurgardens IF": "Djurgarden",
    "Hammarby": "Hammarby",
    "Hammarby IF": "Hammarby",
    "IFK Göteborg": "Goteborg",
    "IFK Goteborg": "Goteborg",
    "Göteborg": "Goteborg",
    "Häcken": "Hacken",
    "Hacken": "Hacken",
    "BK Hacken": "Hacken",
    "Elfsborg": "Elfsborg",
    "IF Elfsborg": "Elfsborg",
    "Norrköping": "Norrkoping",
    "Norrkoping": "Norrkoping",
    "IFK Norrkoping": "Norrkoping",
    "Sirius": "Sirius",
    "IK Sirius": "Sirius",
    "Kalmar": "Kalmar",
    "Kalmar FF": "Kalmar",
    "Värnamo": "Varnamo",
    "Varnamo": "Varnamo",
    "IFK Varnamo": "Varnamo",
    "Halmstad": "Halmstad",
    "Halmstads BK": "Halmstad",
    "GAIS": "GAIS",
    "Mjällby": "Mjallby",
    "Mjallby": "Mjallby",
    "Mjallby AIF": "Mjallby",
    "Varberg": "Varbergs",
    "Varbergs BoIS": "Varbergs",
    "Brommapojkarna": "Brommapojkarna",
    "BP": "Brommapojkarna",
    "IF Brommapojkarna": "Brommapojkarna",
}

# Danish Superliga
DANISH_TEAMS = {
    "FC Copenhagen": "Copenhagen",
    "Copenhagen": "Copenhagen",
    "FCK": "Copenhagen",
    "FC Midtjylland": "Midtjylland",
    "Midtjylland": "Midtjylland",
    "FCM": "Midtjylland",
    "Brøndby": "Brondby",
    "Brondby": "Brondby",
    "Brondby IF": "Brondby",
    "FC Nordsjælland": "Nordsjaelland",
    "Nordsjaelland": "Nordsjaelland",
    "FCN": "Nordsjaelland",
    "AGF Aarhus": "AGF",
    "AGF": "AGF",
    "Aarhus GF": "AGF",
    "Silkeborg": "Silkeborg",
    "Silkeborg IF": "Silkeborg",
    "Randers": "Randers",
    "Randers FC": "Randers",
    "AaB": "Aalborg",
    "AaB Aalborg": "Aalborg",
    "Aalborg": "Aalborg",
    "Viborg": "Viborg",
    "Viborg FF": "Viborg",
    "Odense": "OB",
    "OB": "OB",
    "Odense BK": "OB",
    "Lyngby": "Lyngby",
    "Lyngby BK": "Lyngby",
    "Sonderjyske": "Sonderjyske",
    "SonderjyskE": "Sonderjyske",
    "Vejle": "Vejle",
    "Vejle BK": "Vejle",
    "Horsens": "Horsens",
    "AC Horsens": "Horsens",
}

# Finnish Veikkausliiga
FINNISH_TEAMS = {
    "HJK Helsinki": "HJK",
    "HJK": "HJK",
    "KuPS": "KuPS",
    "Kuopion PS": "KuPS",
    "Ilves": "Ilves",
    "Tampereen Ilves": "Ilves",
    "Inter Turku": "Inter Turku",
    "FC Inter": "Inter Turku",
    "SJK": "SJK",
    "SJK Seinajoki": "SJK",
    "Mariehamn": "Mariehamn",
    "IFK Mariehamn": "Mariehamn",
    "Haka": "Haka",
    "FC Haka": "Haka",
    "HIFK": "HIFK",
    "Helsingin IFK": "HIFK",
    "VPS": "VPS",
    "Vaasan PS": "VPS",
    "Lahti": "Lahti",
    "FC Lahti": "Lahti",
    "Honka": "Honka",
    "FC Honka": "Honka",
    "RoPS": "RoPS",
    "Rovaniemen PS": "RoPS",
    "AC Oulu": "Oulu",
    "Oulu": "Oulu",
    "EIF": "EIF",
    "Gnistan": "Gnistan",
}

# Polish Ekstraklasa
POLISH_TEAMS = {
    "Legia Warszawa": "Legia",
    "Legia Warsaw": "Legia",
    "Legia": "Legia",
    "Lech Poznan": "Lech Poznan",
    "Lech Poznań": "Lech Poznan",
    "Raków Częstochowa": "Rakow",
    "Rakow Czestochowa": "Rakow",
    "KS Rakow Czestochowa": "Rakow",
    "Rakow": "Rakow",
    "Jagiellonia Białystok": "Jagiellonia",
    "Jagiellonia Bialystok": "Jagiellonia",
    "Jagiellonia": "Jagiellonia",
    "Pogoń Szczecin": "Pogon Szczecin",
    "Pogon Szczecin": "Pogon Szczecin",
    "Górnik Zabrze": "Gornik Zabrze",
    "Gornik Zabrze": "Gornik Zabrze",
    "Piast Gliwice": "Piast Gliwice",
    "Piast": "Piast Gliwice",
    "Śląsk Wrocław": "Slask Wroclaw",
    "Slask Wroclaw": "Slask Wroclaw",
    "Wisła Kraków": "Wisla Krakow",
    "Wisla Krakow": "Wisla Krakow",
    "Cracovia": "Cracovia",
    "KS Cracovia": "Cracovia",
    "Zagłębie Lubin": "Zaglebie Lubin",
    "Zaglebie Lubin": "Zaglebie Lubin",
    "Warta Poznań": "Warta Poznan",
    "Warta Poznan": "Warta Poznan",
    "Korona Kielce": "Korona Kielce",
    "Korona": "Korona Kielce",
    "Radomiak": "Radomiak",
    "Radomiak Radom": "Radomiak",
    "Lechia Gdańsk": "Lechia Gdansk",
    "Lechia Gdansk": "Lechia Gdansk",
    "Stal Mielec": "Stal Mielec",
    "Stal": "Stal Mielec",
}

ALL_TEAM_MAPPINGS = {
    **PREMIER_LEAGUE_TEAMS,
    **CHAMPIONSHIP_TEAMS,
    **LEAGUE_ONE_TEAMS,
    **LEAGUE_TWO_TEAMS,
    **LA_LIGA_TEAMS,
    **LA_LIGA_2_TEAMS,
    **BUNDESLIGA_TEAMS,
    **BUNDESLIGA_2_TEAMS,
    **SERIE_A_TEAMS,
    **SERIE_B_TEAMS,
    **LIGUE_1_TEAMS,
    **LIGUE_2_TEAMS,
    **SCOTTISH_TEAMS,
    **EREDIVISIE_TEAMS,
    **EERSTE_DIVISIE_TEAMS,
    **PORTUGUESE_TEAMS,
    **TURKISH_TEAMS,
    **BELGIAN_TEAMS,
    **GREEK_TEAMS,
    **UEFA_TEAMS,
    **NORWEGIAN_TEAMS,
    **SWEDISH_TEAMS,
    **DANISH_TEAMS,
    **FINNISH_TEAMS,
    **POLISH_TEAMS,
}


def normalize_team_name(norsk_tipping_name: str) -> str:
    """
    Convert Norsk Tipping team name to football-data.co.uk format.
    
    Args:
        norsk_tipping_name: Team name from Norsk Tipping site
        
    Returns:
        Standardized team name matching training data, or original if no mapping exists
    """
    normalized = ALL_TEAM_MAPPINGS.get(norsk_tipping_name)
    if normalized is None:
        # Try fuzzy matching for unknown teams
        print(f"Warning: No mapping found for '{norsk_tipping_name}', using as-is")
        return norsk_tipping_name
    return normalized


def get_unmapped_teams(team_names: list[str]) -> list[str]:
    """
    Find team names that don't have mappings yet.
    
    Args:
        team_names: List of team names from Norsk Tipping
        
    Returns:
        List of team names without mappings
    """
    return [name for name in team_names if name not in ALL_TEAM_MAPPINGS]
